* Community Resources

This directory is a host for articles, tutorials, or any knowledge related to /hledger/ and created by the community.

Every hledger user has his work-flow, tips, and ideas on how he improved his usage after using it for some time. This is the place to share that with the rest of the hledger users community.

** Contents

- [[https://github.com/edkedk99/awesome-hledger/blob/master/contrib-resources/emacs-init.org][Beginner Tutorial]] - Tutorial for who is facing hledger for the first time
- [[https://github.com/edkedk99/awesome-hledger/blob/master/contrib-resources/hledger-beginner-tutorial.org][Emacs init]] - Some configurations to add to Emacs init.el to improve the experience of managing journal files in Emacs.

** Contributing 

Our goal is to make contributing the easiest possible, so there two methods to send your article.

*** New Issue 

This is the quick and easy method. Just create an issue and upload your article using markdown or org-mode format. Your file will be added here as soon as possible.

*** Pull request

This is a bit more complex but may be preferred if the author is used to this git feature. The main advantage is that the author will be included in the contributors page in the repository.



